[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "pillow>=11.1.0",
    "psutil>=7.0.0",
    "pyautogui>=0.9.54",
    "pystray>=0.19.5",
]
